import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  memphistSidebar: [
    {
      type: 'category',
      label: 'Bilingual / Двуезично',
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: 'memphis'},
      ],
    },
    {
      type: 'category',
      label: 'Само на български',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'memphis-bg'},
      ],
    },
  ],
  bridgeToLightSidebar: [
    {
      type: 'autogenerated',
      dirName: 'bridge-to-light-bg',
    },
  ],
};

export default sidebars;
