import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  memphistSidebar: [
    {
      type: 'category',
      label: 'The Spurious Rites of Memphis and Misraim',
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: 'memphis'},
      ],
    },
  ],
};

export default sidebars;
